apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdcm-api-logs-pvc
  labels:
    app: pdcm-api-logs-pvc
  namespace: pdcm-api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard-nfs-production