apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: pdcm-api
  labels:
    app: postgrest
    tier: frontend
spec:
  type: NodePort
  ports:
   - port: 80
     nodePort: 3230963
  selector:
    app: postgrest
    tier: frontend