apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: pdcm-api
  labels:
    app: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgrest
        tier: frontend
    spec:
      containers:
        - image: "pdxfinder/pdcm-api:prod"
          name: postgrest
          env:
            - name: PGRST_OPENAPI_SERVER_PROXY_URI
              value: "<PGRST_OPENAPI_SERVER_PROXY_URI>"
            - name: PGRST_DB_ANON_ROLE
              value: "<PGRST_DB_ANON_ROLE>"
            - name: PGRST_DB_SCHEMA
              value: "<PGRST_DB_SCHEMA>"
            - name: PGRST_DB_URI
              value: "<PGRST_DB_URI>"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources: {}
          imagePullPolicy: "Always"
        - image: "pdxfinder/pdcm-api:mail-prod"
          name: create-ticket
          env:
            - name: SENDER_EMAIL
              value: "<SENDER_EMAIL>"
            - name: RECEIVER_EMAIL
              value: "<RECEIVER_EMAIL>"
            - name: SMTP_SERVER
              value: "<SMTP_SERVER>"
            - name: SMTP_PORT
              value: "<SMTP_PORT>"
            - name: SECRET_RECAPTCHA
              value: "<SECRET_RECAPTCHA>"
            - name: HTTP_PROXY
              value: "<HTTP_PROXY>"
            - name: HTTPS_PROXY
              value: "<HTTPS_PROXY>"
          resources: {}
          imagePullPolicy: "Always"
      restartPolicy: Always
status: {}
