apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger
  namespace: pdcm-api
  labels:
    app: swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: swagger
        tier: frontend
    spec:
      containers:
        - env:
            - name: API_URL
              value: "<PGRST_OPENAPI_SERVER_PROXY_URI>"
          image: swaggerapi/swagger-ui
          name: swagger
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}