CREATE USER web_anon;
ALTER USER web_anon WITH PASSWORD 'web_anon';
GRANT USAGE ON SCHEMA pdcm TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA pdcm GRANT SELECT ON TABLES TO web_anon;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO web_anon;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO web_anon;

