apiVersion: v1
kind: ConfigMap
metadata:
  name: pdcm-api-postgres-config
  namespace: pdcm-api
data:
  POSTGRES_DB: pdcm
  POSTGRES_USER: pdcm_ro
  POSTGRES_PASSWORD: PDCMxdF&(*eqrt%^#1hRT
  PGDATA: /var/lib/postgresql/data/pgdata
  JDK_JAVA_OPTIONS: -Dhttps.proxyHost=hh-wwwcache.ebi.ac.uk -Dhttps.proxyPort=3128 -Dhttp.proxyHost=hh-wwwcache.ebi.ac.uk -Dhttp.proxyPort=3128
  HTTP_PROXY: "http://hh-wwwcache.ebi.ac.uk:3128"
  HTTPS_PROXY: "http://hh-wwwcache.ebi.ac.uk:3128"
  http_proxy: "http://hh-wwwcache.ebi.ac.uk:3128"
  https_proxy: "http://hh-wwwcache.ebi.ac.uk:3128"
  no_proxy: "localhost,.cluster.local"

