apiVersion: v1
kind: Service
metadata:
  name: create-ticket-dev
  namespace: pdcm-api-dev
  labels:
    app: create-ticket-dev
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30001
  selector:
    app: create-ticket-dev
    tier: frontend
