apiVersion: v1
kind: Service
metadata:
  name: postgrest-dev
  namespace: pdcm-api-dev
  labels:
    app: postgrest-dev
    tier: frontend
spec:
  type: NodePort
  ports:
   - port: 80
     nodePort: 3230963
  selector:
    app: postgrest-dev
    tier: frontend