apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: pdcm-api
    tier: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: pdcm-api
    tier: postgres

