apiVersion: v1
kind: Service
metadata:
  name: swagger
  namespace: pdcm-api-dev
  labels:
    app: swagger
    tier: frontend
spec:
  type: NodePort
  ports:
   - port: 8080
  selector:
    app: swagger
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger
  namespace: pdcm-api-dev
  labels:
    app: swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: swagger
        tier: frontend
    spec:
      containers:
        - env:
            - name: API_URL
              value: "http://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:30593"
          image: swaggerapi/swagger-ui
          name: swagger
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: pdcm-api-dev
  labels:
    app: postgrest
    tier: frontend
spec:
  type: NodePort
  ports:
   - port: 3000
  selector:
    app: postgrest
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: pdcm-api-dev
  labels:
    app: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
      tier: frontend
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: postgrest
        tier: frontend
    spec:
      containers:
        - env:
            - name: PGRST_OPENAPI_SERVER_PROXY_URI
              value: "http://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:30593"
            - name: PGRST_DB_ANON_ROLE
              value: web_anon
            - name: PGRST_DB_SCHEMA
              value: public
            - name: PGRST_DB_URI
              value: postgres://web_anon:web_anon@postgres:5432/pdcm
          image: postgrest/postgrest:latest
          name: postgrest
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}

